### PR TITLE
fix: check directory before call delete on iOS

### LINKED ISSUE #1020: `clear` should not throw if the db hasn't been created yet
### What happened?

```
WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Failed to delete storage directory.Error Domain=NSCocoaErrorDomain Code=4 "“RCTAsyncLocalStorage” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/mobile/Containers/Data/Application/C716D281-73E6-43CC-9951-ACE53CB23C88/Documents/ExponentExperienceData/%40anonymous%2Fapp-d771027f-1b8a-4905-82e8-0b5bef0f00b0/RCTAsyncLocalStorage, NSUnderlyingError=0x2803286c0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

### Version

1.19.3

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
> npx react-native info
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: "(12) x64 AMD Ryzen 5 5600 6-Core Processor              "
  Memory: 16.06 GB / 31.91 GB
Binaries:
  Node:
    version: 20.2.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.7.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.5.33424.131 (Visual Studio Community 2022)
Languages:
  Java:
    version: 11.0.20.1
    path: C:\Program Files\Eclipse Adoptium\jdk-11.0.20.101-hotspot\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to Reproduce

```js
useEffect(() => {
    (async () => {
        await AsyncStorage.clear();
    })();
}, []);
```

### PR DESCRIPTION
**Pull request by camilossantos2809**
## Summary

Before executing the `clear` method on iOS, check if the directory exists using `RCTGetStorageDirectory` to avoid throwing an error.

Fixes #1020 

## Test Plan

To test this change I created an app from scratch and call `await AsyncStorage.clear()`.
The component code is available on [gist](https://gist.github.com/camilossantos2809/94af62fd65dce53d1cf77430369cbf92)

before:

https://github.com/react-native-async-storage/async-storage/assets/20076881/0a7e7881-6404-4260-bc58-d23179b29f18

after:

https://github.com/react-native-async-storage/async-storage/assets/20076881/5cafc379-839d-45cf-9c0b-76a2855358e0

### CODE REVIEW

File: packages/default-storage/ios/RNCAsyncStorage.mm [hunk 1]
```diff
@@ -869,8 +869,14 @@ - (BOOL)_passthroughDelegate
 
     [_manifest removeAllObjects];
     [RCTGetCache() removeAllObjects];
-    NSDictionary *error = RCTDeleteStorageDirectory();
```
Comment (tido64) [inline packages/default-storage/ios/RNCAsyncStorage.mm:872]: I think it would be simpler if we check whether `error.code == NSFileNoSuchFileError` in `RCTDeleteStorageDirectory()` and ignore it.

**Review by tido64 — COMMENTED** [review]
Thanks for submitting this fix!

File: packages/default-storage/ios/RNCAsyncStorage.mm (hunk 1 above)
Comment (camilossantos2809) [reply packages/default-storage/ios/RNCAsyncStorage.mm]: yeah, it works and is also more clean, thanks for that.
I'm kinda new on Objective-C, I only return nil to ignore, if it was better to return another thing I could change again.

File: packages/default-storage/ios/RNCAsyncStorage.mm [hunk 2]
```diff
@@ -250,6 +250,9 @@ static dispatch_queue_t RCTGetMethodQueue()
     NSError *error;
     [[NSFileManager defaultManager] removeItemAtPath:RCTGetStorageDirectory() error:&error];
     RCTHasCreatedStorageDirectory = NO;
+    if (error.code == NSFileNoSuchFileError) {
+        return nil;
+    }
     return error ? RCTMakeError(@"Failed to delete storage directory.", error, nil) : nil;
```
Comment (tido64) [inline packages/default-storage/ios/RNCAsyncStorage.mm:256]: Nit:
```suggestion
    if (error && error.code != NSFileNoSuchFileError) {
        return RCTMakeError(@"Failed to delete storage directory.", error, nil);
    }
    return nil;
```

**Review by tido64 — APPROVED** [review]
Thanks again. I left only a minor nitpick.

**Review by krizzu — APPROVED** [review]
Thanks!
